name: Contribution Pac-Man

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update Pac-Man
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
