name: Contribution Pac-Man

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: abozanona/pacman-contribution-graph@7332e1de7903ab780c3692a4127a59cc13872daa # main as of 2026-10-01
        with:
          github_user_name: ${{ github.repository_owner }}
          games: pacman

      - uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update Pac-Man
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
